### ISSUE TITLE
Getting lower coverage

### ISSUE THREAD

**Issue by TriplEight** [marco-c/rust-code-coverage-sample#1]
Hello, I'm trying to make use of the source-based coverage and keep getting 0.0% covered.
I'm not quite certain if I'm using the flags wrong, or missed a dependency somewhere. i.e. it's not mentioned anywhere that clang/llvm should be 12, but I tried with 7, 8 and 12 and got the same result anyway.

The repo is https://github.com/TriplEight/cargo-contract
To conveniently repro the issue, you can run it in container
`docker run -it --rm docker.io/paritytech/contracts-ci-linux:production`

```
#!/bin/bash

RUSTFLAGS="-Zinstrument-coverage"
RUSTDOCFLAGS="-Zinstrument-coverage -Zunstable-options --persist-doctests target/debug/doctestbins"

rustup component add llvm-tools-preview

cargo +nightly build --verbose --workspace
cargo +nightly test --verbose --workspace --no-run

grcov . --binary-path ./target/debug/ -s . -t html --branch --ignore-not-existing -o ./coverage/
# grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing -o ./lcov-w-branch.info
```

**Comment by TriplEight** [comment]
Maybe this is not the best example, here's another one:

The repo is https://github.com/paritytech/ink . It's covered [pretty well](https://codecov.io/gh/paritytech/ink/tree/0faafaf4eee7b8875285b7d0aa454382fc4b9dfd) and here [with branches](https://codecov.io/gh/Robbepop/ink/tree/0faafaf4eee7b8875285b7d0aa454382fc4b9dfd). It uses [the following](https://github.com/paritytech/ink/blob/master/.gitlab-ci.yml#L174) setup (pre source-based `grcov` + `rust-covfix`).

To repro this you may want to use ` docker run -it --rm docker.io/paritytech/ink-ci-linux:production`

```
#!/bin/bash

RUSTFLAGS="-Zinstrument-coverage"
RUSTDOCFLAGS="-Zinstrument-coverage -Zunstable-options --persist-doctests target/debug/doctestbins"
unset RUSTC_WRAPPER;
rustup component add llvm-tools-preview;

cargo build --all-features --workspace
cargo test --all-features --workspace --no-run --message-format=json

# 14:18:37 [ERROR] FN 'ink_env::backend::ReturnFlags::set_reverted' duplicated for 'crates/env/src/backend.rs' in a lcov file
grcov --binary-path ./target/debug/ -s . -t html --branch --ignore-not-existing -o ./coverage/ .
# grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing -o ./lcov-w-branch.info
```
And I'm [getting](https://codecov.io/gh/TriplEight/ink/tree/4238f958595f9f0b42e33011bb53e1847e6d3ba5) more lines, which is wrong and much less covered lines and branches.

**Comment by marco-c** [comment]
@TriplEight could you file an issue on https://github.com/mozilla/grcov instead?

Unfortunately I don't have a lot of time to look into these issues at the moment, but I will try to do it as soon as I can.
