### ISSUE TITLE
Zero coverage reported with current Rust nightly toolchain

### ISSUE THREAD

**Issue by scouten** [marco-c/rust-code-coverage-sample#2]
Ran this repo with the current Rust nightly toolchain.

The report shows zero coverage.

**Comment by marco-c** [comment]
I can't reproduce. Are you using Linux?

**Comment by haowqs** [comment]
learnRust/rust-code-coverage-sample$ rustup -V
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.56.0-nightly (08095fc1f 2021-07-26)`
learnRust/rust-code-coverage-sample$ bash run_source_cov.sh
![image](https://user-images.githubusercontent.com/39472702/127114706-c50fa60a-f066-4f35-b580-be0fee1e50ae.png)
- Is this result correct?

**Comment by marco-c** [comment]
No, it isn't.
Did you install the `llvm-tools-preview` component?
Can you share the logs when you run the steps (build, run, grcov execution) from the sample?

**Comment by haowqs** [comment]
I installed llvm-tools-preview.
rust-code-coverage-sample$ rustup component list | grep llvm-tools-preview
llvm-tools-preview-x86_64-unknown-linux-gnu (installed)
**execution:**
```rust-code-coverage-sample$ rm -rf ./target *.prof*
rust-code-coverage-sample$ export RUSTFLAGS="-Zinstrument-coverage"
rust-code-coverage-sample$ cargo build -v
   Compiling rust-code-coverage-sample v0.1.0 (/home/tiano/learnRust/rust-code-coverage-sample)
     Running `rustc --crate-name rust_code_coverage_sample src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=0eaa9b0460e38d32 -C extra-filename=-0eaa9b0460e38d32 --out-dir /home/tiano/learnRust/rust-code-coverage-sample/target/debug/deps -C incremental=/home/tiano/learnRust/rust-code-coverage-sample/target/debug/incremental -L dependency=/home/tiano/learnRust/rust-code-coverage-sample/target/debug/deps -Zinstrument-coverage`
    Finished dev [unoptimized + debuginfo] target(s) in 0.54s
rust-code-coverage-sample$ cargo run -v
       Fresh rust-code-coverage-sample v0.1.0 (/home/tiano/learnRust/rust-code-coverage-sample)
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/rust-code-coverage-sample`
rust-code-coverage-sample$ grcov . --binary-path ./target/debug -s . -t html --branch --ignore-not-existing -o ./target/debug/coverage/
```

**Comment by haowqs** [comment]
I add `export LLVM_PROFILE_FILE="your_name-%p-%m.profraw"`
result not zero
![image](https://user-images.githubusercontent.com/39472702/127291136-34115093-1ecf-44d3-87ec-92b4610e818f.png)
**Is this result correct?**

**Comment by marco-c** [comment]
Yeah, that's correct. IDK why that would be needed though!
